name: Build and Test Python Shiny App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t python-shiny-app .

    - name: Run Docker container
      run: |
        docker run -d --name shiny-container -p 8000:8000 python-shiny-app
        sleep 30
        docker logs shiny-container

    - name: Test health of Shiny app
      run: |
        curl --fail http://localhost:8000 || (echo "App failed to respond" && exit 1)

    - name: Cleanup
      run: docker rm -f shiny-container

